## 00. Pytorch Fundamentals

In [2]:
import torch

In [3]:
print(torch.__version__)

2.2.1


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Introduction to tensors

In [9]:
# pytorch tensors are created using "torch.tensor()"
scalar_num = torch.tensor(5)

In [10]:
scalar_num

tensor(5)

In [11]:
scalar_num.item()

5

In [24]:
scalar_num.shape

torch.Size([])

In [12]:
scalar_num.type()

'torch.LongTensor'

In [13]:
scalar_num.ndim

0

In [14]:
vector_num = torch.tensor([5,3])

In [19]:
vector_num.ndim

1

In [20]:
vector_num

tensor([5, 3])

In [23]:
vector_num.shape

torch.Size([2])

In [28]:
vector_num.ndim
# The vector ndim can be checked by the number of brackets before starting of the number 
# Also as the scalar has 0 dim, vector can be understood as an item having 1 dimension

1

In [25]:
# the shape is 2 as the vector has both magnitude and direction
# while a scalar does not have any shape, it just has a single number

In [29]:
## MATRIX

In [31]:
MATRIX = torch.tensor([[2, 3],
                       [4, 5]])

In [33]:
MATRIX

tensor([[2, 3],
        [4, 5]])

In [34]:
MATRIX.ndim

2

In [35]:
MATRIX[1]

tensor([4, 5])

In [37]:
MATRIX[0]

tensor([2, 3])

In [38]:
MATRIX.shape

torch.Size([2, 2])

In [39]:
## TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

In [40]:
TENSOR.ndim

3

In [41]:
TENSOR.shape

torch.Size([1, 3, 3])

## Dimension(dim)
##### index -    0 1 2
##### dimesnion- 1 3 3

torch.Size([1, 3, 3])

That means there's 1 dimension of 3 by 3 matrix.

In [44]:
TENSOR[0] # 0th dimension
# the far left [ is the 0th dimension

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

#### the second bracket matches with the second 3, which says there are 3 rows of data and the third 3 matches with the number of columns in the matrix
refer -  https://www.learnpytorch.io/00_pytorch_fundamentals/

In [49]:
TENSOR_1 = torch.tensor([[[[1,2,3,4],
                          [5,6,7,4],
                          [6,6,6,6]]]])

In [50]:
TENSOR_1.shape

torch.Size([1, 1, 3, 4])

In [ ]:
TENSOR_2 = torch.tensor([[[[1,2,3,4],
                          [5,6,7,4],
                          [6,6,6,6]]]])

In [51]:
## Random Tensor
random_tensor = torch.rand(4,5)

In [52]:
random_tensor

tensor([[0.7482, 0.0992, 0.8893, 0.2259, 0.7204],
        [0.2942, 0.2181, 0.3505, 0.3422, 0.5413],
        [0.2257, 0.1055, 0.5995, 0.8466, 0.0772],
        [0.4861, 0.3263, 0.6476, 0.6332, 0.1553]])

In [53]:
random_tensor.shape

torch.Size([4, 5])

In [54]:
random_tensor.ndim

2

In [58]:
# creating a 2 dim random_tensor
random_tensor_1 = torch.rand(2,3,2)

In [59]:
random_tensor_1

tensor([[[0.4370, 0.4889],
         [0.2748, 0.7986],
         [0.3882, 0.5140]],

        [[0.9329, 0.1334],
         [0.7268, 0.5026],
         [0.4955, 0.3233]]])

In [60]:
# 1,4,5
random_tensor_1.shape

torch.Size([2, 3, 2])

In [69]:
torch.rand(size = (5,3,4))

tensor([[[0.6751, 0.6193, 0.4684, 0.1430],
         [0.1036, 0.0680, 0.7630, 0.5953],
         [0.0889, 0.7451, 0.3008, 0.0432]],

        [[0.1044, 0.0210, 0.8685, 0.1370],
         [0.5907, 0.7341, 0.6880, 0.0499],
         [0.5356, 0.8125, 0.0539, 0.2807]],

        [[0.3890, 0.4110, 0.0784, 0.7332],
         [0.9943, 0.8386, 0.7625, 0.6436],
         [0.5044, 0.7970, 0.9863, 0.7522]],

        [[0.2998, 0.0788, 0.4364, 0.4792],
         [0.7997, 0.5898, 0.4837, 0.0275],
         [0.7030, 0.8884, 0.3972, 0.7442]],

        [[0.0086, 0.5486, 0.1588, 0.7542],
         [0.4821, 0.8188, 0.8286, 0.4951],
         [0.2511, 0.7919, 0.4585, 0.5608]]])

In [70]:
random_tensor_1.dtype

torch.float32

In [72]:
# checking the flexibility of random matrix generation
# general image matrix size
random_image_size_tensor = torch.rand(size = (224,224,3))

In [73]:
random_image_size_tensor

tensor([[[0.6640, 0.5943, 0.6673],
         [0.0258, 0.6458, 0.8062],
         [0.5330, 0.9888, 0.8794],
         ...,
         [0.7965, 0.7765, 0.4101],
         [0.6524, 0.4381, 0.0200],
         [0.7712, 0.5214, 0.9587]],

        [[0.6875, 0.9770, 0.2030],
         [0.6008, 0.4195, 0.9765],
         [0.9797, 0.6611, 0.1458],
         ...,
         [0.2912, 0.0059, 0.2464],
         [0.6768, 0.1134, 0.7998],
         [0.3744, 0.6250, 0.5523]],

        [[0.0806, 0.7456, 0.0409],
         [0.3013, 0.2061, 0.5254],
         [0.5653, 0.6477, 0.1467],
         ...,
         [0.1241, 0.6488, 0.5631],
         [0.8516, 0.6322, 0.9765],
         [0.2719, 0.0725, 0.7077]],

        ...,

        [[0.6154, 0.9830, 0.4565],
         [0.9764, 0.0427, 0.6397],
         [0.3514, 0.4244, 0.8441],
         ...,
         [0.9699, 0.5258, 0.5499],
         [0.5486, 0.5823, 0.1434],
         [0.3771, 0.7598, 0.6294]],

        [[0.1982, 0.5442, 0.4699],
         [0.9535, 0.7851, 0.3417],
         [0.

### Zeros and Ones Tensors

In [74]:
# creating a tensor with all zeros
zeros_tensor = torch.zeros(size = (4,3))

In [76]:
zeros_tensor, zeros_tensor.dtype

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 torch.float32)

In [78]:
ones_tensor = torch.ones(size = (5,2,5))
ones_tensor, ones_tensor.dtype

(tensor([[[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]],
 
         [[1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1.]]]),
 torch.float32)

#### Creating a Range in Tensors

In [79]:
# torch.arange(start, end, stop)

In [86]:
zero_to_tensor = torch.arange(1,92,8)
zero_to_tensor

tensor([ 1,  9, 17, 25, 33, 41, 49, 57, 65, 73, 81, 89])

In [87]:
# copying the shape of the input tensor with zeros or ones
zeros_copy_tensor = torch.zeros_like(zero_to_tensor)
zeros_copy_tensor

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [91]:
ones_like_tensor = torch.ones_like(zeros_tensor)
ones_like_tensor

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [92]:
# default datatype for tensors is float32

In [93]:
## Default datatype for tensors is float32
default_tensor = torch.tensor([3.0,6.0,8.0],
                              dtype = None,
                              device = None,
                              requires_grad = False)
# dtype = None, when given like this, it defaults to torch.float32 which is the default dtype for torch tensor
#device = None, if device = torch.cude in this case we are using nvidia's gpu for operations,
# if not it defaults to default device
# requires_grad = False, if it is True, the operations performed on the tensor are recorded
# I think this is used during backpropogation

default_tensor, default_tensor.shape, default_tensor.dtype, default_tensor.device

(tensor([3., 6., 8.]), torch.Size([3]), torch.float32, device(type='cpu'))

In [96]:
# creating a tensor with float 16 dtype
float_16_tensor = torch.tensor([3.0,6.0,8.0],
                               dtype = torch.float16,
                               device = None,
                               requires_grad = False)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 8.], dtype=torch.float16), torch.float16)

In [99]:
float_8_tensor = torch.tensor([4.0,2.0,6.9],
                              dtype = torch.float8,
                              device = None,
                              requires_grad = False)
float_8_tensor, float_8_tensor.shape

AttributeError: module 'torch' has no attribute 'float8'

In [101]:
mul_tensor_1 = float_16_tensor * default_tensor
mul_tensor_1, mul_tensor_1.dtype

(tensor([ 9., 36., 64.]), torch.float32)

In [102]:
int_32_tensor = torch.tensor([4,5,6],
                             dtype = torch.int32)
int_32_tensor, int_32_tensor.dtype

(tensor([4, 5, 6], dtype=torch.int32), torch.int32)

In [104]:
default_tensor * int_32_tensor

tensor([12., 30., 48.])

## Getting information from tensors
1. Tensors not right datatype - to get the datatype from tensors -> torch.dtype
2. Tensors not right shape - to get the shape from tensors -> torch.shape
3. Tensors not on right device - to get the device it is stored on -> torch.device

In [106]:
some_rand_tensor = torch.rand(4,6)
some_rand_tensor

tensor([[0.4314, 0.0829, 0.9730, 0.9862, 0.9619, 0.5421],
        [0.6227, 0.4629, 0.1393, 0.6280, 0.3360, 0.1651],
        [0.1216, 0.6507, 0.0762, 0.4053, 0.7994, 0.3649],
        [0.5707, 0.2492, 0.5174, 0.4544, 0.7533, 0.2361]])

In [108]:
# Fetching details from the tensor
print(f"The shape of the tensor is - {some_rand_tensor.shape}")
print(f"The datatype of the tensors is - {some_rand_tensor.dtype}")
print(f"The device of the tensors is - {some_rand_tensor.device}")

The shape of the tensor is - torch.Size([4, 6])
The datatype of the tensors is - torch.float32
The device of the tensors is - cpu


### Manipulating Tensors (tensor operations)

1. Addition
2. Multiplication (Element-Wise)
3. Substraction
4. Division
5. Matrix Multiplication

In [110]:
# Create a sample tensor
sample_tensor = torch.tensor([3,4,5])
sample_tensor+10

tensor([13, 14, 15])

In [111]:
# Addition
sample_tensor + 100

tensor([103, 104, 105])

In [112]:
# Multiplication
sample_tensor *100

tensor([300, 400, 500])

In [116]:
## Matrix multiplication
mat_1 = torch.rand(size = (3,4))
mat_1

tensor([[0.0285, 0.4367, 0.8307, 0.2851],
        [0.8542, 0.6414, 0.9404, 0.2221],
        [0.5263, 0.3346, 0.0341, 0.6752]])

In [119]:
mat_2 = torch.rand(size = (4,4))
mat_2

tensor([[0.0890, 0.8522, 0.7749, 0.0494],
        [0.5547, 0.5735, 0.5228, 0.6593],
        [0.8513, 0.0652, 0.4090, 0.8431],
        [0.3780, 0.4819, 0.0278, 0.1426]])

In [120]:
torch.matmul(mat_1, mat_2)

tensor([[1.0597, 0.4662, 0.5980, 1.0303],
        [1.3163, 1.2642, 1.3880, 1.2896],
        [0.5167, 0.9679, 0.6154, 0.3716]])

In [121]:
mat_1 @ mat_2

tensor([[1.0597, 0.4662, 0.5980, 1.0303],
        [1.3163, 1.2642, 1.3880, 1.2896],
        [0.5167, 0.9679, 0.6154, 0.3716]])

In [123]:
mat_3 = torch.rand(size = (3,4))
mat_3, mat_3.shape

(tensor([[0.2701, 0.3610, 0.4778, 0.9843],
         [0.1624, 0.4312, 0.2696, 0.9493],
         [0.0557, 0.0845, 0.4933, 0.6158]]),
 torch.Size([3, 4]))

In [124]:
mat_4 = torch.rand(size = (3,4))
mat_4, mat_4.shape

(tensor([[0.4646, 0.9350, 0.9207, 0.7288],
         [0.6069, 0.2801, 0.0501, 0.2848],
         [0.5683, 0.4529, 0.5319, 0.6600]]),
 torch.Size([3, 4]))

In [125]:
torch.mm(mat_3, mat_4)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x4 and 3x4)

In [127]:
# Torch Transpose to transpose one matrix and perform matrix multiplication
mat_4.T.shape

torch.Size([4, 3])

In [129]:
mat_4_transpose = mat_4.T
mat_4_transpose, mat_4_transpose.shape

(tensor([[0.4646, 0.6069, 0.5683],
         [0.9350, 0.2801, 0.4529],
         [0.9207, 0.0501, 0.5319],
         [0.7288, 0.2848, 0.6600]]),
 torch.Size([4, 3]))

In [130]:
mat_3.shape

torch.Size([3, 4])

In [132]:
torch.mm(mat_3, mat_4_transpose), torch.mm(mat_3, mat_4_transpose).shape

(tensor([[1.6202, 0.5692, 1.2208],
         [1.4186, 0.5032, 1.0576],
         [1.0078, 0.2575, 0.7388]]),
 torch.Size([3, 3]))

## Finding the min, max, mean, sum, etc (tensor aggregation)

In [138]:
x = torch.arange(1,50,10)

In [139]:
x

tensor([ 1, 11, 21, 31, 41])

In [142]:
torch.min(x), torch.max(x)

(tensor(1), tensor(41))

In [143]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [145]:
torch.mean(x.type(torch.float16))

tensor(21., dtype=torch.float16)

In [148]:
x.type(torch.float32).mean()

tensor(21.)

### Finding the positional Min and Max

In [150]:
x.argmax(), x.argmin()

(tensor(4), tensor(0))

In [152]:
x[4]

tensor(41)

### Reshaping, Stacking, Squeezing and Unsqueezing Tensors
1. Reshaping - reshapes an input tensor to the desired shape
2. View - Returns a view of the input tensor shape but keeps the same memory as the original tensor
3. Stacking - Combines multiple tensors side by side (hastack), Colbines multiple tensors on top of each other(vstack)
4. Squeeze - removes all '1' dimension from the tensor
5. Unsqueeze - adds '1' dimension to the vector
6. Permute - Returns a view of the input with dimensions swapped in the desired way

In [169]:
y = torch.arange(1.5,11)

In [170]:
y, y.shape

(tensor([ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000,  8.5000,
          9.5000, 10.5000]),
 torch.Size([10]))

In [158]:
# Reshape - 
# adds an extra dimension to the tensor
y_reshaped = y.reshape(1,6)

RuntimeError: shape '[1, 6]' is invalid for input of size 7

In [171]:
y_reshaped = y.reshape(2,5)
y_reshaped, y_reshaped.shape

(tensor([[ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000],
         [ 6.5000,  7.5000,  8.5000,  9.5000, 10.5000]]),
 torch.Size([2, 5]))

In [174]:
y_reshaped = y.reshape(5,2)
y_reshaped, y_reshaped.shape

(tensor([[ 1.5000,  2.5000],
         [ 3.5000,  4.5000],
         [ 5.5000,  6.5000],
         [ 7.5000,  8.5000],
         [ 9.5000, 10.5000]]),
 torch.Size([5, 2]))

In [180]:
# Changing the view
z = y.view(1,10)
z, z.shape, y.shape
# changing z, changes y

(tensor([[ 1.5000,  2.5000,  3.5000,  4.5000,  5.5000,  6.5000,  7.5000,  8.5000,
           9.5000, 10.5000]]),
 torch.Size([1, 10]),
 torch.Size([10]))

In [185]:
z[:,3] = 55.9
z, y

(tensor([[ 1.5000,  2.5000,  3.5000, 55.9000,  5.5000,  6.5000,  7.5000,  8.5000,
           9.5000, 10.5000]]),
 tensor([ 1.5000,  2.5000,  3.5000, 55.9000,  5.5000,  6.5000,  7.5000,  8.5000,
          9.5000, 10.5000]))

In [187]:
## Stacking Tensors on top of each other
y_stacked = torch.stack([y,y,y], dim = 1)
y_stacked

tensor([[ 1.5000,  1.5000,  1.5000],
        [ 2.5000,  2.5000,  2.5000],
        [ 3.5000,  3.5000,  3.5000],
        [55.9000, 55.9000, 55.9000],
        [ 5.5000,  5.5000,  5.5000],
        [ 6.5000,  6.5000,  6.5000],
        [ 7.5000,  7.5000,  7.5000],
        [ 8.5000,  8.5000,  8.5000],
        [ 9.5000,  9.5000,  9.5000],
        [10.5000, 10.5000, 10.5000]])

In [189]:
y_stacked = torch.stack([y,y], dim = 0)
y_stacked

tensor([[ 1.5000,  2.5000,  3.5000, 55.9000,  5.5000,  6.5000,  7.5000,  8.5000,
          9.5000, 10.5000],
        [ 1.5000,  2.5000,  3.5000, 55.9000,  5.5000,  6.5000,  7.5000,  8.5000,
          9.5000, 10.5000]])

### torch.squeeze() -  Returns a tensor with all specified dimensions of input of size 1 removed.

In [193]:
y = torch.arange(1,9,0.9)
y,y.shape

(tensor([1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000, 8.2000]),
 torch.Size([9]))

In [196]:
y_reshaped = y.reshape(1,9)
y_reshaped, y_reshaped.shape

(tensor([[1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000, 8.2000]]),
 torch.Size([1, 9]))

In [198]:
y_reshaped.squeeze(), y_reshaped.squeeze().shape, y_reshaped.shape

(tensor([1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000, 8.2000]),
 torch.Size([9]),
 torch.Size([1, 9]))

In [199]:
y_reshaped.squeeze(1)

tensor([[1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000, 8.2000]])

In [200]:
y_reshaped = y.reshape(1,1,9)
y_reshaped, y_reshaped.shape

(tensor([[[1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000,
           8.2000]]]),
 torch.Size([1, 1, 9]))

In [204]:
y_reshaped.squeeze(), y_reshaped.squeeze().shape

(tensor([1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000, 8.2000]),
 torch.Size([9]))

In [210]:
print(f"The original tensor is {y_reshaped}")
print(f"The shape of the originl tensor is {y_reshaped.shape}")
print("\n")
print(f"\nThe squeezed tensor is(it removes all the one dimensions from the vectors) - {y_reshaped.squeeze()}")
print(f"\nThe shape of the squeezed tensor of squeeze dimension is {y_reshaped.squeeze().shape}")

The original tensor is tensor([[[1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000,
          8.2000]]])
The shape of the originl tensor is torch.Size([1, 1, 9])



The squeezed tensor is(it removes all the one dimensions from the vectors) - tensor([1.0000, 1.9000, 2.8000, 3.7000, 4.6000, 5.5000, 6.4000, 7.3000, 8.2000])

The shape of the squeezed tensor of squeeze dimension is torch.Size([9])


### torch.unsqueeze() -  adds a single dimension to the target tensor at a specific dimension
Here specific dimension in the sense when we are getting the shape of the tensor, we have dimensions like - 0,1,2.              
When we mention in the unsqueeze the dimension, the changes happens in that dimension specifically

In [212]:
x= torch.arange(5,20,2)
x, x.shape

(tensor([ 5,  7,  9, 11, 13, 15, 17, 19]), torch.Size([8]))

In [223]:
print(f"The original tensor is {x}")
print(f"The shape of the originl tensor is {x.shape}")

The original tensor is tensor([ 5,  7,  9, 11, 13, 15, 17, 19])
The shape of the originl tensor is torch.Size([8])


In [224]:
# unsqueezing at the 0th dimension - 
print(f"The original tensor is {x}")
print(f"The unsqueezed tensor is {x.unsqueeze(dim = 0)}")
print(f"The shape of the unsqueezed tensor is {x.unsqueeze(dim = 0).shape}")

The original tensor is tensor([ 5,  7,  9, 11, 13, 15, 17, 19])
The unsqueezed tensor is tensor([[ 5,  7,  9, 11, 13, 15, 17, 19]])
The shape of the unsqueezed tensor is torch.Size([1, 8])


In [226]:
# unsqueezing at the 1th dimension -  it will change into 8,1 matrix
print(f"The original tensor is {x}")
print(f"The unsqueezed tensor is\n {x.unsqueeze(dim = 1)}")
print(f"The shape of the unsqueezed tensor is {x.unsqueeze(dim = 1).shape}")

The original tensor is tensor([ 5,  7,  9, 11, 13, 15, 17, 19])
The unsqueezed tensor is
 tensor([[ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])
The shape of the unsqueezed tensor is torch.Size([8, 1])


In [228]:
# unsqueezing at the -1th dimension - 
print(f"The original tensor is {x}")
print(f"The shape of the originl tensor is {x.shape}")
print(f"The unsqueezed tensor is\n {x.unsqueeze(dim = -1)}")
print(f"The shape of the unsqueezed tensor is {x.unsqueeze(dim = -1).shape}")

The original tensor is tensor([ 5,  7,  9, 11, 13, 15, 17, 19])
The shape of the originl tensor is torch.Size([8])
The unsqueezed tensor is
 tensor([[ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]])
The shape of the unsqueezed tensor is torch.Size([8, 1])


In [229]:
# unsqueezing at the -1th dimension - 
print(f"The original tensor is {x}")
print(f"The shape of the originl tensor is {x.shape}")
print(f"The unsqueezed tensor is\n {x.unsqueeze(dim = -2)}")
print(f"The shape of the unsqueezed tensor is {x.unsqueeze(dim = -2).shape}")

The original tensor is tensor([ 5,  7,  9, 11, 13, 15, 17, 19])
The shape of the originl tensor is torch.Size([8])
The unsqueezed tensor is
 tensor([[ 5,  7,  9, 11, 13, 15, 17, 19]])
The shape of the unsqueezed tensor is torch.Size([1, 8])


## Torch Permute

In [230]:
x = torch.randn(2, 3, 5)

In [231]:
x

tensor([[[-0.5649, -0.6694,  0.2793,  0.1273,  1.6874],
         [-0.4471, -0.4358, -0.6261,  2.0579,  0.6755],
         [-0.4839, -0.5092, -0.8075, -0.3421, -1.0141]],

        [[-1.5333, -1.8683, -0.8993, -0.1407, -0.7839],
         [-1.0712,  0.4771, -0.6805, -0.1231,  0.1059],
         [ 0.0283, -1.5163, -1.4571, -1.3441, -1.9353]]])

In [233]:
# torch. permute rearranges the dimension of the input with the given permutations
x.permute(2,1,0), x.permute(2,1,0).shape
#5,3,2

(tensor([[[-0.5649, -1.5333],
          [-0.4471, -1.0712],
          [-0.4839,  0.0283]],
 
         [[-0.6694, -1.8683],
          [-0.4358,  0.4771],
          [-0.5092, -1.5163]],
 
         [[ 0.2793, -0.8993],
          [-0.6261, -0.6805],
          [-0.8075, -1.4571]],
 
         [[ 0.1273, -0.1407],
          [ 2.0579, -0.1231],
          [-0.3421, -1.3441]],
 
         [[ 1.6874, -0.7839],
          [ 0.6755,  0.1059],
          [-1.0141, -1.9353]]]),
 torch.Size([5, 3, 2]))

## Pytorch Tensors and Numpy
Pytorch has functionality to interact with numpy.
* Your Data in Numpy Array ----> Want in Pytorch Tensor - `torch.from_numpy(ndarray)`
* Pytorch Tensor ----> Numpy Array - `torch.Tensor.numpy()`

In [236]:
# Numpy array to tensor
import numpy as np

array_1 = np.arange(1,15,2)
array_1
tensor_1 = torch.arange(1,20,3)
tensor_1, array_1

(tensor([ 1,  4,  7, 10, 13, 16, 19]), array([ 1,  3,  5,  7,  9, 11, 13]))

In [240]:
new_torch = torch.from_numpy(array_1)
new_torch, new_torch.dtype

(tensor([ 1,  3,  5,  7,  9, 11, 13]), torch.int64)

In [238]:
# when converting from numpy to tensor, pytorch will keep the numpys original datatype of float64 unless
# specially mentioned

In [244]:
new_torch = torch.from_numpy(array_1).type(torch.float32)
new_torch, new_torch.dtype

(tensor([ 1.,  3.,  5.,  7.,  9., 11., 13.]), torch.float32)

In [246]:
# Tensor to Numpy array
new_array = tensor_1.numpy()
new_array, new_array.dtype

(array([ 1,  4,  7, 10, 13, 16, 19]), dtype('int64'))

## Device Agnostic Code

In [247]:
device = "cude" if torch.cuda.is_available() else "cpu"
device

'cpu'